version: '3'
services:
  mediawiki:
    build: .
    image: dtek/mediawiki:latest
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
      - parsoid
    links:
      - db
      - parsoid
    volumes:
      - ./.htaccess:/var/www/html/.htaccess
      - ./images:/var/www/html/images
      - ./logo.png:/var/www/html/resources/assets/logo.png
      - ./logo.svg:/var/www/html/resources/assets/logo.svg

      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./rewrite.load:/etc/apache2/mods-enabled/rewrite.load
    environment:
      MW_REST_DOMAIN: wiki.dtek.se
  db:
    image: mariadb
    restart: always
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./mariadb/data:/var/lib/mysql
  parsoid:
    image: thenets/parsoid:0.10.0
    restart: always
    volumes:
      - ./run-parsoid.sh:/run-parsoid.sh
    environment:
      PARSOID_DOMAIN_dummy: http://dummy
      PARSOID_NUM_WORKERS: ncpu
